In [20]:
# Answer to question number : 4

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# Task 1:
iris = load_iris()
sepal_length_np = iris.data[:, 0]  # Select sepal length column
sepal_width_np = iris.data[:, 1]  # Select sepal width column

# Task 2:
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

# 1. Calculate mean, median, and standard deviation
print("Descriptive Statistics:")
print(iris_df.describe())

# 2. Group by species and calculate average sepal and petal length
species_avg = iris_df.groupby('species')[['sepal length (cm)', 'petal length (cm)']].mean()
print("\nAverage Sepal and Petal Length by Species:")
print(species_avg)

# 3. Filter by sepal length
filtered_df = iris_df[iris_df['sepal length (cm)'] > 5.0]
print("\nFlowers with Sepal Length > 5.0 cm:")
print(filtered_df)

Descriptive Statistics:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000  

Average Sepal and Petal Length by Species:
            sepal length (cm)  petal length (cm)
species                                         
setosa        

<ipython-input-20-7e188e8a8e33>:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  species_avg = iris_df.groupby('species')[['sepal length (cm)', 'petal length (cm)']].mean()


In [19]:
# Answer to the question number 3

import numpy as np
import csv
import pickle

# Task 1:
my_list = ['apple', 'banana', 'cherry', 'date', 'elderberry']


with open('my_list.txt', 'w') as file:
    for item in my_list:
        file.write(f"{item}\n")

print("List saved to my_list.txt.")


with open('my_list.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    for item in my_list:
        writer.writerow([item])

print("List saved to my_list.csv.")

my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

np.savetxt('my_array.csv', my_array, delimiter=',', fmt='%d')
read_array = np.loadtxt('my_array.csv', delimiter=',')

print("2D array saved to my_array.csv and read back:")
print(read_array)


with open('my_array.pkl', 'wb') as pickle_file:
    pickle.dump(my_array, pickle_file)

with open('my_array.pkl', 'rb') as pickle_file:
    loaded_array = pickle.load(pickle_file)

print("Array saved to my_array.pkl and loaded back:")
print(loaded_array)


List saved to my_list.txt.
List saved to my_list.csv.
2D array saved to my_array.csv and read back:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Array saved to my_array.pkl and loaded back:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
#answer to the question number:2

def my_triangle(b, h):
    # Calculate the area of the triangle
    area = 0.5 * b * h
    return area


base = float(input("Enter the base of the triangle: "))
height = float(input("Enter the height of the triangle: "))
print(my_triangle(base, height))  # This will output 25.0



Enter the base of the triangle: 1
Enter the height of the triangle: 1
0.5


In [23]:
#answer to the question no:1

def total_sales(store_data):

    total_sales_per_product = {}
    for store_name, products in store_data.items():
        for product_name, quantity in products.items():
            if product_name in total_sales_per_product:
                total_sales_per_product[product_name] += quantity
            else:
                total_sales_per_product[product_name] = quantity
    return total_sales_per_product

def store_with_max_sales(store_data):
    max_sales = 0
    max_sales_store = None
    for store_name, products in store_data.items():
        total_sales_store = sum(products.values())
        if total_sales_store > max_sales:
            max_sales = total_sales_store
            max_sales_store = store_name
    return max_sales_store

# Example usage:
store_data = {
    "Store A": {"Product 1": 10, "Product 2": 15, "Product 3": 8},
    "Store B": {"Product 1": 12, "Product 2": 7, "Product 3": 11},
    "Store C": {"Product 1": 5, "Product 2": 18, "Product 3": 6}
}

total_sales_per_product = total_sales(store_data)
print("Total sales per product:", total_sales_per_product)

store_with_max_sales = store_with_max_sales(store_data)
print("Store with maximum sales:", store_with_max_sales)

Total sales per product: {'Product 1': 27, 'Product 2': 40, 'Product 3': 25}
Store with maximum sales: Store A
